<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\StaffRole;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Creates every role and permission the application needs.
 *
 * Staff permissions (`Update:User`, `ViewAny:Role`) are generated by Filament
 * Shield, one per resource action. Shield regenerates them as resources are
 * added, so mirroring them in an enum would drift the first time someone adds
 * a resource. They are generated here instead, which is what makes a fresh
 * clone come up with a working staff panel.
 *
 * Idempotent: safe to re-run after adding a role, permission or resource.
 */
class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $this->seedStaffPermissions();

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    private function seedStaffPermissions(): void
    {
        // --option=permissions and --ignore-existing-policies matter: the plain
        // command also (re)generates policies, and it will happily overwrite a
        // hand-written one.
        Artisan::call('shield:generate', [
            '--all' => true,
            '--panel' => 'admin',
            '--option' => 'permissions',
            '--ignore-existing-policies' => true,
            '--no-interaction' => true,
            '--silent' => true,
        ]);

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        /** @var array<int, string> $shieldPermissions */
        $shieldPermissions = Permission::query()
            ->where('name', 'like', '%:%')
            ->whereRaw("name ~ '^[A-Z]'")
            ->pluck('name')
            ->all();

        // Super admins get everything. Shield can also intercept the gate, but
        // granting explicitly keeps the role meaningful in tests and in its UI.
        $this->role(StaffRole::SuperAdmin->value)->syncPermissions($shieldPermissions);

        // Support is read-only by default; widen it in Shield's UI, not here.
        $this->role(StaffRole::Support->value)->syncPermissions(
            array_values(array_filter(
                $shieldPermissions,
                static fn (string $name): bool => str_starts_with($name, 'View'),
            ))
        );
    }

    private function role(string $name): Role
    {
        return Role::firstOrCreate(
            ['name' => $name, 'guard_name' => 'web'],
            ['name' => $name, 'guard_name' => 'web'],
        );
    }
}
