<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\StaffRole;
use App\Enums\TeamPermission;
use App\Enums\TeamRole;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Creates every role and permission the application needs.
 *
 * There are two permission vocabularies, deliberately:
 *
 *  - Tenant permissions (`member:add`, `team:update`) come from the typed
 *    TeamPermission enum. They are product behaviour, referenced from
 *    application code, so they belong in code.
 *
 *  - Staff permissions (`Update:Team`, `ViewAny:User`) are generated by
 *    Filament Shield, one per resource action. Shield regenerates them as
 *    resources are added, so mirroring them in an enum would drift the first
 *    time someone adds a resource. They are generated here instead, which is
 *    what makes a fresh clone come up with a working staff panel.
 *
 * Idempotent: safe to re-run after adding a role, permission or resource.
 */
class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $this->seedTenantPermissions();
        $this->seedStaffPermissions();

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    /**
     * Tenant roles, derived from the enum that already maps them.
     *
     * team_id is null on the role *definition*, which makes each role available
     * to every team. The assignment in model_has_roles carries the team scope.
     */
    private function seedTenantPermissions(): void
    {
        foreach (TeamPermission::cases() as $permission) {
            Permission::findOrCreate($permission->value, 'web');
        }

        foreach (TeamRole::cases() as $role) {
            $this->role($role->value)->syncPermissions(
                array_map(fn (TeamPermission $p): string => $p->value, $role->permissions())
            );
        }
    }

    private function seedStaffPermissions(): void
    {
        // --option=permissions and --ignore-existing-policies matter: the plain
        // command also (re)generates policies, and it will happily overwrite a
        // hand-written one -- it already destroyed TeamPolicy once.
        Artisan::call('shield:generate', [
            '--all' => true,
            '--panel' => 'admin',
            '--option' => 'permissions',
            '--ignore-existing-policies' => true,
            '--no-interaction' => true,
            '--silent' => true,
        ]);

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        /** @var array<int, string> $shieldPermissions */
        $shieldPermissions = Permission::query()
            ->where('name', 'like', '%:%')
            ->whereRaw("name ~ '^[A-Z]'")
            ->pluck('name')
            ->all();

        // Super admins get everything. Shield can also intercept the gate, but
        // granting explicitly keeps the role meaningful in tests and in its UI.
        $this->role(StaffRole::SuperAdmin->value)->syncPermissions($shieldPermissions);

        // Support is read-only by default; widen it in Shield's UI, not here.
        $this->role(StaffRole::Support->value)->syncPermissions(
            array_values(array_filter(
                $shieldPermissions,
                static fn (string $name): bool => str_starts_with($name, 'View'),
            ))
        );
    }

    private function role(string $name): Role
    {
        return Role::firstOrCreate(
            ['name' => $name, 'guard_name' => 'web', 'team_id' => null],
            ['name' => $name, 'guard_name' => 'web', 'team_id' => null],
        );
    }
}
